PUT
http://localhost:8001/key-value/smt
Content-Type: application/json
{"smt": true}


%%%

# Duration: 278 ms
# URL: http://localhost:8001/key-value/smt

# HTTP/1.1 200

@Content-Type: text/plain;charset=UTF-8
@Content-Length: 6
@Date: Sun, 01 Apr 2018 11:26:37 GMT

COMMIT